const soldItemsList = [
  {
    id: 1,
    name: "MCM Rattan Cane Sideboard/ Dresser / Buffet Table",
    currentImage: "/images/mcm-rattan-cane/img1.jpg",
    images: [
      "/images/mcm-rattan-cane/img2.jpg",
      "/images/mcm-rattan-cane/img3.jpg",
      "/images/mcm-rattan-cane/img4.jpg",
      "/images/mcm-rattan-cane/img5.jpg",
      "/images/mcm-rattan-cane/img6.jpg",
      "/images/mcm-rattan-cane/img7.jpg",
    ],
    condition: "Used",
    color: "Olive Green",
    material: "Wood",
    brand: "Mid-Century Modern",
    dimensions: "48 x 31.25 x 17.5",
  },
  {
    id: 2,
    name: "Vintage 1900s Dresser / Sideboard / Credenze With Modern Touch",
    currentImage: "/images/vintage-1900-dresser/img1.jpg",
    images: [
      "/images/vintage-1900-dresser/img2.jpg",
      "/images/vintage-1900-dresser/img3.jpg",
      "/images/vintage-1900-dresser/img4.jpg",
      "/images/vintage-1900-dresser/img5.jpg",
    ],
    condition: "Used",
    color: "Brown",
    material: "Wood",
    brand: "Vintage",
    dimensions: "57 x 26 x 28",
  },
  {
    id: 3,
    name: "Modernized 70s Duo Of Nightstands",
    currentImage: "/images/70s-nightstands/img1.jpg",
    images: [
      "/images/70s-nightstands/img2.jpg",
      "/images/70s-nightstands/img3.jpg",
    ],
    condition: "Used",
    color: "Black",
    material: "Painted Wood",
    brand: "Walter E Smithe",
    dimensions: "24 x 24.3 x 13.2",
  },
  {
    id: 4,
    name: "MCM Dresser / Credenza / TV Stand",
    currentImage: "/images/mcm-credenza/img1.jpg",
    images: [
      "/images/mcm-credenza/img2.jpg",
      "/images/mcm-credenza/img3.jpg",
      "/images/mcm-credenza/img4.jpg",
    ],
    condition: "Used",
    color: "Black",
    material: "Painted Wood",
    brand: "Walter E Smithe",
    dimensions: "24 x 24.3 x 13.2",
  },
  {
    id: 5,
    name: "MCM Corner Vanity / Desk & Anthropologic Mirror & Chair",
    currentImage: "/images/mcm-corner-vanity/img1.jpg",
    images: [
      "/images/mcm-corner-vanity/img2.jpg",
      "/images/mcm-corner-vanity/img3.jpg",
    ],
    condition: "Used",
    color: "Green",
    material: "Painted Wood",
    brand: "Unknown",
    dimensions: "36 x 32 x 33",
  },
  {
    id: 6,
    name: "MCM Vintage Dresser",
    currentImage: "/images/vintage-mcm-dresser/img1.jpg",
    images: [
      "/images/vintage-mcm-dresser/img2.jpg",
      "/images/vintage-mcm-dresser/img3.jpg",
      "/images/vintage-mcm-dresser/img4.jpg",
    ],
    condition: "Used",
    color: "Black",
    material: "Painted Wood",
    brand: "Mid-Century Modern",
    dimensions: "52 x 17.5 x 32",
  },
  {
    id: 7,
    name: "MCM Lowboy & Highboy",
    currentImage: "/images/mcm-low-high/img1.jpg",
    images: ["/images/mcm-low-high/img2.jpg", "/images/mcm-low-high/img3.jpg"],
    condition: "Used",
    color: "Black",
    material: " Red Chestnut Finish / Wood",
    brand: "Vintage",
    dimensions: "Lowboy: 72 x 18 x 30.5 // Highboy: 38 x 18 x 44.2",
  },
  {
    id: 8,
    name: "MCM Large Credenze / Buffet Table / Console Table / Cabinet / TV Stand",
    currentImage: "/images/mcm-large-credenza/img1.jpg",
    images: [
      "/images/mcm-large-credenza/img2.jpg",
      "/images/mcm-large-credenza/img3.jpg",
      "/images/mcm-large-credenza/img4.jpg",
    ],
    condition: "Used",
    color: "Black",
    material: " Red Chestnut Finish / Wood",
    brand: "Vintage",
    dimensions: "Lowboy: 72 x 18 x 30.5 // Highboy: 38 x 18 x 44.2",
  },
];

export default soldItemsList;
